<?php
function get_resource($type)
{
    $resourceDir = opendir(get_stylesheet_directory() . '/emitted-assets/' . $type);
    $allowedSuffixes = ['legacy'];
    $stylesArray = array();

    while ($file = readdir($resourceDir)) {
        if ($file != '.' && $file != '..') {
            $fullName = $file;
            preg_match_all("/^\w+\./", $fullName, $nameMatch, PREG_PATTERN_ORDER);
            preg_match_all("/\.\w+\./", $fullName, $suffixMatch, PREG_PATTERN_ORDER);
            $styleProps = array('fullName' => $fullName, 'name' => str_replace('.', '', $nameMatch[0][0]), 'suffix' => str_replace('.', '', $suffixMatch[0][0]));

            if (!in_array($styleProps['suffix'], $allowedSuffixes)) {
                $styleProps['suffix'] = '';
            }
            array_push($stylesArray, $styleProps);
        }
    }
    return $stylesArray;
}

function should_be_included($resource) {
  global $suffix;

  if ($resource['suffix'] === $suffix || !$resource['suffix'] || strpos($resource['fullName'], '.dev')) {
    return true;
  }
  return false;
}

function load_resources($suffix)
{
    global $theme_path;

    $stylesArray = get_resource('css');
    $scriptsArray = get_resource('js');

    //Take vendors script out of scriptsArray
    $vendorsArray = [];
    foreach ($scriptsArray as $key => $script) {
      if($script['name'] === 'vendors') {
        array_push($vendorsArray, $script);
        unset($scriptsArray[$key]);
      }
    }

    foreach ($stylesArray as $style) {
        if (should_be_included($style)) {
            wp_enqueue_style($style['name'], $theme_path . '/emitted-assets/css/' . $style['fullName'], null);
        }
    }

    //include vendors before other scripts
    foreach ($vendorsArray as $script) {
        if (should_be_included($script)) {
            wp_enqueue_script($script['name'], $theme_path . '/emitted-assets/js/' . $script['fullName'], null, null, true);
        }
    }

    foreach ($scriptsArray as $script) {
        if (should_be_included($script)) {
            wp_enqueue_script($script['name'], $theme_path . '/emitted-assets/js/' . $script['fullName'], ['vendors'], null, true);
        }
    }
}

function load_static_resources() {
  //put here scripts, styles etc. that are not generated by Webpack.
}

function select_resources_to_load()
{
    global $is_IE;
    $suffix = $is_IE ? '.legacy' : '';

    load_resources($suffix);
    load_static_resources();
}

add_action('wp_head', 'select_resources_to_load');

function remove_jquery($scripts)
{
    if (!is_admin()) {
        $scripts->remove('jquery');
    }
}

add_filter('wp_default_scripts', 'remove_jquery');
